-- =============================================================================
-- NexLab — Migration 0002: Ordens de Serviço multi-item
-- Substitui a tabela "demandas" (só continha dado de demonstração) por
-- "ordens_servico" + "ordem_servico_itens": uma Ordem de Serviço (OS) agora
-- pode ter vários serviços, cada um com sua própria cor/arco/valor.
-- Espelha docs/database-schema.md — mantenha os dois em sincronia.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Limpeza do modelo antigo (dado só de demonstração, seguro descartar)
-- -----------------------------------------------------------------------------
drop view if exists vw_relatorio_fechamento_itens;
drop view if exists vw_contas_receber;
drop table if exists notas_servico;
drop table if exists demandas;

-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------
alter type status_demanda rename to status_os;
create type arco_dentario as enum ('superior', 'inferior');

-- -----------------------------------------------------------------------------
-- servicos: tempo médio de conclusão (usado para sugerir a data de entrega)
-- -----------------------------------------------------------------------------
alter table servicos add column tempo_medio_dias int;
comment on column servicos.tempo_medio_dias is 'Dias médios estimados para conclusão — usado para sugerir data de entrega prevista.';

-- -----------------------------------------------------------------------------
-- ordens_servico (era "demandas") — cabeçalho da OS
-- -----------------------------------------------------------------------------
create table ordens_servico (
  id uuid primary key default gen_random_uuid(),
  numero_os bigint generated by default as identity,
  entidade_id uuid not null references entidades (id),
  cliente_final text, -- paciente/consultório final, texto livre (informativo)
  status status_os not null default 'recebido',
  data_recebimento date not null default current_date,
  data_prevista date, -- data de entrega prevista
  data_entrega date, -- data de entrega real
  desconto numeric(10, 2) not null default 0,
  mes_referencia date generated always as (
    -- cast p/ timestamp força a variante IMMUTABLE de date_trunc (ver nota em 0001_init.sql)
    date_trunc('month', coalesce(data_entrega, data_recebimento)::timestamp)::date
  ) stored,
  observacoes text,
  created_by uuid references profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (numero_os)
);

create index idx_os_entidade_mes on ordens_servico (entidade_id, mes_referencia);
create index idx_os_status on ordens_servico (status);
create index idx_os_cliente_final on ordens_servico using gin (cliente_final gin_trgm_ops);

comment on table ordens_servico is 'Ordens de Serviço (OS) — cabeçalho. Os serviços de cada OS ficam em ordem_servico_itens.';
comment on column ordens_servico.cliente_final is 'Nome do paciente/consultório final, texto livre (informativo).';
comment on column ordens_servico.mes_referencia is 'Mês de fechamento (dia 1 ao último dia): usa data_entrega se já entregue, senão data_recebimento.';

create trigger trg_ordens_servico_updated_at before update on ordens_servico
  for each row execute function set_updated_at();

-- -----------------------------------------------------------------------------
-- ordem_servico_itens — cada serviço dentro de uma OS
-- -----------------------------------------------------------------------------
create table ordem_servico_itens (
  id uuid primary key default gen_random_uuid(),
  ordem_id uuid not null references ordens_servico (id) on delete cascade,
  servico_id uuid not null references servicos (id),
  cor text, -- variação de cor do item (livre, ex.: código de cor dental)
  arco arco_dentario, -- superior / inferior, quando aplicável
  quantidade int not null default 1 check (quantidade > 0),
  valor_unitario numeric(10, 2) not null default 0, -- snapshot no momento da criação (editável)
  valor_comissao numeric(10, 2), -- preenchido só quando a entidade da OS é parceiro
  created_at timestamptz not null default now()
);

create index idx_os_itens_ordem on ordem_servico_itens (ordem_id);

comment on table ordem_servico_itens is 'Serviços de uma Ordem de Serviço — cor e arco são atributos do item, não do catálogo.';

-- -----------------------------------------------------------------------------
-- notas_servico — agora referencia ordens_servico
-- -----------------------------------------------------------------------------
create table notas_servico (
  id uuid primary key default gen_random_uuid(),
  numero text not null unique,
  ordem_id uuid not null references ordens_servico (id),
  entidade_id uuid not null references entidades (id),
  valor_total numeric(10, 2) not null,
  data_emissao timestamptz not null default now(),
  created_by uuid references profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

comment on table notas_servico is 'Nota de Serviço estilo cupom, sem valor fiscal — histórico de emissões por OS.';

-- -----------------------------------------------------------------------------
-- Views (recalculadas por ordem, agregando os itens)
-- -----------------------------------------------------------------------------
create view vw_contas_receber as
with totais_ordem as (
  select
    o.id as ordem_id,
    o.entidade_id,
    o.mes_referencia,
    o.desconto,
    sum(
      (case when e.tipo = 'parceiro' then coalesce(i.valor_comissao, 0) else i.valor_unitario end)
      * i.quantidade
    ) as subtotal
  from ordens_servico o
  join entidades e on e.id = o.entidade_id
  join ordem_servico_itens i on i.ordem_id = o.id
  where o.status = 'entregue'
  group by o.id, o.entidade_id, o.mes_referencia, o.desconto
)
select
  t.entidade_id,
  e.tipo,
  e.nome as entidade_nome,
  t.mes_referencia,
  count(*) as qtd_ordens,
  sum(t.subtotal - t.desconto) as valor_total,
  coalesce(f.status, 'aberto') as status_fechamento,
  f.data_pagamento
from totais_ordem t
join entidades e on e.id = t.entidade_id
left join fechamentos f on f.entidade_id = t.entidade_id and f.mes_referencia = t.mes_referencia
group by t.entidade_id, e.tipo, e.nome, t.mes_referencia, f.status, f.data_pagamento;

comment on view vw_contas_receber is 'Base da tela Contas a Receber: uma linha por entidade/mês com o total a receber (soma dos itens das OS entregues).';

create view vw_relatorio_fechamento_itens as
select
  o.id as ordem_id,
  o.entidade_id,
  e.nome as entidade_nome,
  e.tipo as entidade_tipo,
  o.mes_referencia,
  o.numero_os,
  o.data_recebimento,
  o.data_entrega,
  o.cliente_final,
  s.nome as servico_nome,
  i.cor,
  i.arco,
  i.quantidade,
  o.status,
  i.valor_unitario,
  i.valor_comissao,
  o.desconto
from ordens_servico o
join entidades e on e.id = o.entidade_id
join ordem_servico_itens i on i.ordem_id = o.id
join servicos s on s.id = i.servico_id
where o.status = 'entregue';

comment on view vw_relatorio_fechamento_itens is 'Linha a linha por item de OS entregue — alimenta o PDF de Relatório de Fechamento (Fase 4).';

-- -----------------------------------------------------------------------------
-- Row Level Security (mesmo padrão de 0001_init.sql)
-- -----------------------------------------------------------------------------
alter table ordens_servico enable row level security;
alter table ordem_servico_itens enable row level security;
alter table notas_servico enable row level security;

create policy "os_select" on ordens_servico for select using (is_active_user());
create policy "os_insert" on ordens_servico for insert with check (is_active_user());
create policy "os_update" on ordens_servico for update using (is_active_user());
create policy "os_delete" on ordens_servico for delete using (is_admin_user());

create policy "os_itens_select" on ordem_servico_itens for select using (is_active_user());
create policy "os_itens_insert" on ordem_servico_itens for insert with check (is_active_user());
create policy "os_itens_update" on ordem_servico_itens for update using (is_active_user());
create policy "os_itens_delete" on ordem_servico_itens for delete using (is_active_user());

create policy "notas_servico_select" on notas_servico for select using (is_active_user());
create policy "notas_servico_insert" on notas_servico for insert with check (is_active_user());
